# Presidential Speeches Configuration
BASE_URL:       http://www.presidency.ucsb.edu/ws/index.php
BASE_URL_PRINT: http://www.presidency.ucsb.edu/ws/print.php

# Directory to store the resulting files
BASE_DIR:       speeches

# Begin and end dates to search, in form YYYY-MM-DD
BEGIN_DATE:     2000-01-01
END_DATE:       2016-12-31

# Filter by Leader(s): names must match the forms in the list below exactly
LEADER_FILTER:  []

# Limit by number of presidency (single presidency only)
PRESIDENCY: 43

ALL_PRESIDENTS:
    1: 'George Washington'
    2: 'John Adams'
    3: 'Thomas Jefferson'
    4: 'James Madison'
    5: 'James Monroe'
    6: 'John Quincy Adams'
    7: 'Andrew Jackson'
    8: 'Martin van Buren'
    9: 'William Henry Harrison'
    10: 'John Tyler'
    11: 'James K. Polk'
    12: 'Zachary Taylor'
    13: 'Millard Fillmore'
    14: 'Franklin Pierce'
    15: 'James Buchanan'
    16: 'Abraham Lincoln'
    17: 'Andrew Johnson'
    18: 'Ulysses S. Grant'
    19: 'Rutherford B Hayes'
    20: 'James A. Garfield'
    21: 'Chester A. Arthur'
    22: 'Grover Cleveland'
    23: 'Benjamin Harrison'
    24: 'Grover Cleveland'
    25: 'William McKinley'
    26: 'Theodore Roosevelt'
    27: 'William Howard Taft'
    28: 'Woodrow Wilson'
    29: 'Warren G. Harding'
    30: 'Calvin Coolidge'
    31: 'Herbert Hoover'
    32: 'Franklin D. Roosevelt'
    33: 'Harry S. Truman'
    34: 'Dwight D. Eisenhower'
    35: 'John F. Kennedy'
    36: 'Lyndon B. Johnson'
    37: 'Richard Nixon'
    38: 'Gerald R. Ford'
    39: 'Jimmy Carter'
    40: 'Ronald Reagan'
    41: 'George Bush'
    42: 'William J. Clinton'
    43: 'George W. Bush'
    44: 'Barack Obama'
